layout_spectrum: 0.23220866546034813
typography_spectrum: 0.7234829133376479
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.4123270749114454
  lightness: 0.382698493078351
  saturation: 0.021883196430280805
  rhythmicContrast: 0.6215822224039584
opengraph:
  image: null
  type: 'https://www.facebook.com/CORTINASNEDINA/'
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Garden Marketing Digital
  email: salmo@gardendigital.com.br
  url: gardendigital.com.br
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fd9cac16-3455-45e0-b254-034276a7a10c.png
name: 'Mais que perto, juntos!'
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Nedina Cortinas
description: Cortinas & Persianas
purpose: []
