typography_spectrum: 0
color:
  brandColors:
    - '#ffffff'
    - '#2d3190'
    - '#0095d8'
    - '#908fc5'
    - '#8ed7f7'
  brandStrength: 0.625
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5166
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fd9cac16-3455-45e0-b254-034276a7a10c.png
name: NEDINA CORTINAS
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Nedina Cortinas
description: Cortinas & Persianas
purpose: []
